/**
 * GluMira™ — Supabase Generated Types
 * Auto-generated by scripts/generate-types.ts
 * DO NOT EDIT MANUALLY — run `pnpm generate:types` to regenerate
 *
 * Covers all tables across waves 1–19:
 *   patient_profiles, glucose_readings, insulin_doses,
 *   meals, notifications, beta_feedback, beta_participants,
 *   clinician_notes, school_care_plans
 *
 * Generated: 2026-03-26T00:00:00.000Z
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// ─── Database root ───────────────────────────────────────────────────────────

export interface Database {
  public: {
    Tables: {
      patient_profiles: PatientProfilesTable;
      glucose_readings: GlucoseReadingsTable;
      insulin_doses: InsulinDosesTable;
      meals: MealsTable;
      notifications: NotificationsTable;
      beta_feedback: BetaFeedbackTable;
      beta_participants: BetaParticipantsTable;
      clinician_notes: ClinicianNotesTable;
      school_care_plans: SchoolCarePlansTable;
    };
    Views: {
      admin_stats_view: AdminStatsView;
      feedback_summary_view: FeedbackSummaryView;
      open_concerns_view: OpenConcernsView;
    };
    Functions: {
      get_tir_summary: GetTirSummaryFunction;
      get_iob_current: GetIobCurrentFunction;
    };
    Enums: {
      diabetes_type: "T1D" | "T2D" | "LADA" | "Other";
      glucose_units: "mmol/L" | "mg/dL";
      insulin_concentration: 100 | 200 | 300 | 500;
      note_category: "general" | "clinical" | "alert" | "follow-up" | "school";
      note_priority: "low" | "medium" | "high" | "urgent";
      feedback_category: "bug" | "feature" | "ux" | "general" | "praise";
      participant_status: "invited" | "onboarding" | "active" | "paused" | "completed" | "withdrawn";
      notification_type: "hypo_alert" | "hyper_alert" | "iob_warning" | "system" | "reminder";
      user_role: "patient" | "clinician" | "admin";
    };
  };
}

// ─── patient_profiles ────────────────────────────────────────────────────────

export interface PatientProfileRow {
  id: string;
  user_id: string;
  display_name: string;
  dob: string | null;
  diabetes_type: Database["public"]["Enums"]["diabetes_type"];
  insulin_type: string;
  insulin_concentration: Database["public"]["Enums"]["insulin_concentration"];
  weight_kg: number | null;
  height_cm: number | null;
  glucose_units: Database["public"]["Enums"]["glucose_units"];
  active_meal_regime: string | null;
  notifications_enabled: boolean;
  hypo_alert_threshold: number;
  hyper_alert_threshold: number;
  role: Database["public"]["Enums"]["user_role"];
  created_at: string;
  updated_at: string;
}

export interface PatientProfileInsert extends Omit<PatientProfileRow, "id" | "created_at" | "updated_at"> {
  id?: string;
  created_at?: string;
  updated_at?: string;
}

export type PatientProfileUpdate = Partial<PatientProfileInsert>;

interface PatientProfilesTable {
  Row: PatientProfileRow;
  Insert: PatientProfileInsert;
  Update: PatientProfileUpdate;
}

// ─── glucose_readings ────────────────────────────────────────────────────────

export interface GlucoseReadingRow {
  id: string;
  user_id: string;
  glucose_mmol: number;
  recorded_at: string;
  source: "manual" | "nightscout" | "cgm_direct" | "libre";
  trend: "rising_fast" | "rising" | "flat" | "falling" | "falling_fast" | null;
  notes: string | null;
  created_at: string;
}

export interface GlucoseReadingInsert extends Omit<GlucoseReadingRow, "id" | "created_at"> {
  id?: string;
  created_at?: string;
}

export type GlucoseReadingUpdate = Partial<GlucoseReadingInsert>;

interface GlucoseReadingsTable {
  Row: GlucoseReadingRow;
  Insert: GlucoseReadingInsert;
  Update: GlucoseReadingUpdate;
}

// ─── insulin_doses ───────────────────────────────────────────────────────────

export interface InsulinDoseRow {
  id: string;
  user_id: string;
  units: number;
  insulin_type: string;
  concentration: Database["public"]["Enums"]["insulin_concentration"];
  administered_at: string;
  dose_type: "bolus" | "correction" | "basal";
  meal_id: string | null;
  notes: string | null;
  created_at: string;
}

export interface InsulinDoseInsert extends Omit<InsulinDoseRow, "id" | "created_at"> {
  id?: string;
  created_at?: string;
}

export type InsulinDoseUpdate = Partial<InsulinDoseInsert>;

interface InsulinDosesTable {
  Row: InsulinDoseRow;
  Insert: InsulinDoseInsert;
  Update: InsulinDoseUpdate;
}

// ─── meals ───────────────────────────────────────────────────────────────────

export interface MealRow {
  id: string;
  user_id: string;
  regime: string;
  carbs_g: number;
  description: string | null;
  eaten_at: string;
  icr_used: number | null;
  bolus_units: number | null;
  created_at: string;
}

export interface MealInsert extends Omit<MealRow, "id" | "created_at"> {
  id?: string;
  created_at?: string;
}

export type MealUpdate = Partial<MealInsert>;

interface MealsTable {
  Row: MealRow;
  Insert: MealInsert;
  Update: MealUpdate;
}

// ─── notifications ───────────────────────────────────────────────────────────

export interface NotificationRow {
  id: string;
  user_id: string;
  type: Database["public"]["Enums"]["notification_type"];
  title: string;
  body: string;
  data: Json | null;
  read: boolean;
  dismissed: boolean;
  push_sent: boolean;
  created_at: string;
}

export interface NotificationInsert extends Omit<NotificationRow, "id" | "created_at"> {
  id?: string;
  created_at?: string;
}

export type NotificationUpdate = Partial<NotificationInsert>;

interface NotificationsTable {
  Row: NotificationRow;
  Insert: NotificationInsert;
  Update: NotificationUpdate;
}

// ─── beta_feedback ───────────────────────────────────────────────────────────

export interface BetaFeedbackRow {
  id: string;
  user_id: string;
  participant_id: string | null;
  rating: 1 | 2 | 3 | 4 | 5;
  category: Database["public"]["Enums"]["feedback_category"];
  comment: string;
  page: string | null;
  reviewed: boolean;
  archived: boolean;
  created_at: string;
}

export interface BetaFeedbackInsert extends Omit<BetaFeedbackRow, "id" | "created_at"> {
  id?: string;
  created_at?: string;
}

export type BetaFeedbackUpdate = Partial<BetaFeedbackInsert>;

interface BetaFeedbackTable {
  Row: BetaFeedbackRow;
  Insert: BetaFeedbackInsert;
  Update: BetaFeedbackUpdate;
}

// ─── beta_participants ───────────────────────────────────────────────────────

export interface BetaParticipantRow {
  id: string;
  user_id: string | null;
  participant_id: string;
  email: string;
  name: string | null;
  country: string | null;
  diabetes_type: Database["public"]["Enums"]["diabetes_type"] | null;
  status: Database["public"]["Enums"]["participant_status"];
  nightscout_url: string | null;
  onboarded_at: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface BetaParticipantInsert extends Omit<BetaParticipantRow, "id" | "created_at" | "updated_at"> {
  id?: string;
  created_at?: string;
  updated_at?: string;
}

export type BetaParticipantUpdate = Partial<BetaParticipantInsert>;

interface BetaParticipantsTable {
  Row: BetaParticipantRow;
  Insert: BetaParticipantInsert;
  Update: BetaParticipantUpdate;
}

// ─── clinician_notes ─────────────────────────────────────────────────────────

export interface ClinicianNoteRow {
  id: string;
  clinician_id: string;
  patient_id: string;
  content: string;
  category: Database["public"]["Enums"]["note_category"];
  priority: Database["public"]["Enums"]["note_priority"];
  follow_up_date: string | null;
  resolved: boolean;
  created_at: string;
  updated_at: string;
}

export interface ClinicianNoteInsert extends Omit<ClinicianNoteRow, "id" | "created_at" | "updated_at"> {
  id?: string;
  created_at?: string;
  updated_at?: string;
}

export type ClinicianNoteUpdate = Partial<ClinicianNoteInsert>;

interface ClinicianNotesTable {
  Row: ClinicianNoteRow;
  Insert: ClinicianNoteInsert;
  Update: ClinicianNoteUpdate;
}

// ─── school_care_plans ───────────────────────────────────────────────────────

export interface SchoolCarePlanRow {
  id: string;
  patient_id: string;
  clinician_id: string | null;
  academic_year: string;
  school_name: string;
  teacher_name: string | null;
  emergency_contact_name: string;
  emergency_contact_phone: string;
  regime: string;
  hypo_treatment: string;
  hyper_action: string;
  html_content: string;
  generated_at: string;
  created_at: string;
}

export interface SchoolCarePlanInsert extends Omit<SchoolCarePlanRow, "id" | "created_at"> {
  id?: string;
  created_at?: string;
}

export type SchoolCarePlanUpdate = Partial<SchoolCarePlanInsert>;

interface SchoolCarePlansTable {
  Row: SchoolCarePlanRow;
  Insert: SchoolCarePlanInsert;
  Update: SchoolCarePlanUpdate;
}

// ─── Views ───────────────────────────────────────────────────────────────────

export interface AdminStatsViewRow {
  total_users: number;
  total_readings: number;
  total_doses: number;
  total_meals: number;
  total_feedback: number;
  avg_feedback_rating: number;
  active_participants: number;
  readings_last_7d: number;
  doses_last_7d: number;
}

interface AdminStatsView {
  Row: AdminStatsViewRow;
}

export interface FeedbackSummaryViewRow {
  category: string;
  count: number;
  avg_rating: number;
  unreviewed: number;
}

interface FeedbackSummaryView {
  Row: FeedbackSummaryViewRow;
}

export interface OpenConcernViewRow {
  id: string;
  clinician_id: string;
  patient_id: string;
  content: string;
  category: string;
  priority: string;
  follow_up_date: string | null;
  days_overdue: number;
  created_at: string;
}

interface OpenConcernsView {
  Row: OpenConcernViewRow;
}

// ─── Functions ───────────────────────────────────────────────────────────────

interface GetTirSummaryFunction {
  Args: { p_user_id: string; p_days: number };
  Returns: {
    tir_pct: number;
    tbr_pct: number;
    tar_pct: number;
    avg_glucose_mmol: number;
    cv_pct: number;
    gmi: number;
    reading_count: number;
  };
}

interface GetIobCurrentFunction {
  Args: { p_user_id: string };
  Returns: {
    total_iob: number;
    dose_count: number;
    risk_tier: "safe" | "caution" | "high" | "critical";
    oldest_active_dose_min: number;
  };
}

// ─── Convenience re-exports ──────────────────────────────────────────────────

export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];

export type InsertTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];

export type UpdateTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];

export type Enums<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T];

// ─── Typed Supabase client helper ────────────────────────────────────────────

export type TypedSupabaseClient = ReturnType<
  typeof import("@supabase/supabase-js").createClient<Database>
>;
