import { useState } from "react";
const TITLE = "Low GI";
const DESC = "Glycaemic Index focused — choosing foods that release glucose slowly.";
const ICON = "📉";
const COLOR = "#0891B2";
const DAILY_CARBS = "130-180g";
const MACRO = "45% carb / 25% protein / 30% fat";
const CONSIDERATIONS = ["Focuses on quality of carbs, not just quantity","Low GI foods (< 55) cause slower, gentler glucose rise","Reduces post-meal spikes without strict carb limits","Combining high-GI with protein/fat lowers overall GI","Cooking method changes GI — al dente pasta < overcooked","GI values vary by person — CGM helps personalise"];
const FOODS = ["Basmati rice (low GI vs white)","Sweet potato","Oats (steel-cut)","Legumes and lentils","Most fruits (apple, pear, berries)","Wholegrain sourdough bread","Pasta (al dente)","Quinoa","Barley","Nuts and seeds"];
const AVOID = ["White bread","Instant rice","Cornflakes and puffed cereals","Watermelon","White potatoes (baked/mashed)","Rice cakes","Instant oats","Pretzels","Short-grain sticky rice","Overcooked pasta"];
export default function LowGIModule(){const[tab,setTab]=useState("overview");return(<div style={{minHeight:"100vh",background:"#f8f9fa",padding:"24px 16px"}}><div style={{maxWidth:720,margin:"0 auto"}}><div style={{display:"flex",alignItems:"center",gap:12,marginBottom:24}}><span style={{fontSize:32}}>{ICON}</span><div><h1 style={{margin:0,fontSize:22,color:"#1a2a5e"}}>{TITLE} Diet Module</h1><p style={{margin:"4px 0 0",fontSize:13,color:"#64748b"}}>{DESC}</p></div></div><div style={{display:"flex",gap:8,marginBottom:20,flexWrap:"wrap"}}>{["overview","foods","considerations"].map(t=>(<button key={t} onClick={()=>setTab(t)} style={{padding:"8px 16px",borderRadius:8,border:`1px solid ${tab===t?COLOR:"#e2e8f0"}`,background:tab===t?`${COLOR}10`:"white",color:tab===t?COLOR:"#64748b",fontWeight:tab===t?600:400,cursor:"pointer",fontSize:13,textTransform:"capitalize"}}>{t}</button>))}</div>{tab==="overview"&&(<div style={{background:"white",borderRadius:12,padding:20,border:"1px solid #e2e8f0"}}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16,marginBottom:16}}><div style={{padding:14,borderRadius:8,background:`${COLOR}08`,border:`1px solid ${COLOR}20`}}><div style={{fontSize:11,color:"#64748b",marginBottom:4}}>Daily Carbs</div><div style={{fontSize:18,fontWeight:700,color:COLOR}}>{DAILY_CARBS}</div></div><div style={{padding:14,borderRadius:8,background:"#f1f5f9"}}><div style={{fontSize:11,color:"#64748b",marginBottom:4}}>Macro Split</div><div style={{fontSize:13,fontWeight:600,color:"#1a2a5e"}}>{MACRO}</div></div></div></div>)}{tab==="foods"&&(<div style={{background:"white",borderRadius:12,padding:20,border:"1px solid #e2e8f0"}}><h3 style={{color:"#059669",fontSize:14,margin:"0 0 12px"}}>✅ Include</h3>{FOODS.map((f:string,i:number)=>(<div key={i} style={{padding:"8px 12px",borderBottom:"1px solid #f1f5f9",fontSize:13,color:"#1a2a5e"}}>{f}</div>))}<h3 style={{color:"#dc2626",fontSize:14,margin:"20px 0 12px"}}>❌ Avoid</h3>{AVOID.map((f:string,i:number)=>(<div key={i} style={{padding:"8px 12px",borderBottom:"1px solid #f1f5f9",fontSize:13,color:"#64748b"}}>{f}</div>))}</div>)}{tab==="considerations"&&(<div style={{background:"white",borderRadius:12,padding:20,border:"1px solid #e2e8f0"}}>{CONSIDERATIONS.map((c:string,i:number)=>(<div key={i} style={{display:"flex",gap:10,padding:"10px 0",borderBottom:"1px solid #f1f5f9"}}><span style={{color:COLOR,fontWeight:700,fontSize:14}}>→</span><span style={{fontSize:13,color:"#1a2a5e",lineHeight:1.5}}>{c}</span></div>))}</div>)}<p style={{marginTop:24,fontSize:11,color:"#94a3b8",textAlign:"center"}}>GluMira™ is an educational platform and does not constitute medical advice.</p></div></div>);}
