/**
 * GluMira™ School Care Plan — Generator
 * Produces HTML care plan documents from patient profile data.
 */

export interface SchoolCarePlanInput {
  patientName: string;
  dateOfBirth: string;
  regimeName: string;
  insulinType: string;
  hypoThresholdMmol: number;
  hyperThresholdMmol: number;
  schoolName?: string;
  emergencyContact?: string;
  emergencyPhone?: string;
  allergies?: string[];
  notes?: string;
}

export function validateSchoolCarePlanInput(input: Partial<SchoolCarePlanInput> | undefined): string[] {
  const errors: string[] = [];
  if (!input) return ["Input is required"];
  if (!input.patientName?.trim()) errors.push("patientName is required");
  if (!input.dateOfBirth) errors.push("dateOfBirth is required");
  if (!input.regimeName?.trim()) errors.push("regimeName is required");
  if (!input.insulinType?.trim()) errors.push("insulinType is required");
  if (typeof input.hypoThresholdMmol !== "number" || input.hypoThresholdMmol <= 0) errors.push("hypoThresholdMmol must be a positive number");
  if (typeof input.hyperThresholdMmol !== "number" || input.hyperThresholdMmol <= 0) errors.push("hyperThresholdMmol must be a positive number");
  return errors;
}

export function generateSchoolCarePlan(input: SchoolCarePlanInput) {
  const hypoMgdl = Math.round(input.hypoThresholdMmol * 18.0182);
  const hyperMgdl = Math.round(input.hyperThresholdMmol * 18.0182);
  const generatedAt = new Date().toISOString();

  const html = `
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>School Care Plan — ${esc(input.patientName)}</title>
<style>
  body { font-family: 'DM Sans', system-ui, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px 24px; color: #1a2a5e; }
  h1 { font-family: 'Playfair Display', Georgia, serif; font-size: 24px; margin-bottom: 4px; }
  h2 { font-size: 16px; margin-top: 24px; color: #2ab5c1; text-transform: uppercase; letter-spacing: 0.5px; }
  table { width: 100%; border-collapse: collapse; margin-top: 8px; }
  th, td { text-align: left; padding: 8px 12px; border: 1px solid #dee2e6; font-size: 13px; }
  th { background: #f8fafd; font-weight: 600; }
  .alert { background: #fef3cd; border: 1px solid #f59e0b; padding: 12px; border-radius: 8px; font-size: 13px; margin-top: 16px; }
  .footer { margin-top: 32px; font-size: 11px; color: #94a3b8; }
</style>
</head>
<body>
  <h1>School Care Plan</h1>
  <p style="font-size:13px;color:#52667a;">Generated by GluMira™ — ${generatedAt.slice(0, 10)}</p>

  <h2>Patient Details</h2>
  <table>
    <tr><th>Name</th><td>${esc(input.patientName)}</td></tr>
    <tr><th>Date of Birth</th><td>${esc(input.dateOfBirth)}</td></tr>
    <tr><th>Insulin Regime</th><td>${esc(input.regimeName)}</td></tr>
    <tr><th>Insulin Type</th><td>${esc(input.insulinType)}</td></tr>
    ${input.schoolName ? `<tr><th>School</th><td>${esc(input.schoolName)}</td></tr>` : ""}
    ${input.allergies?.length ? `<tr><th>Allergies</th><td>${input.allergies.map(esc).join(", ")}</td></tr>` : ""}
  </table>

  <h2>Glucose Thresholds</h2>
  <table>
    <tr><th>Hypo threshold</th><td>${input.hypoThresholdMmol} mmol/L (${hypoMgdl} mg/dL)</td></tr>
    <tr><th>Hyper threshold</th><td>${input.hyperThresholdMmol} mmol/L (${hyperMgdl} mg/dL)</td></tr>
  </table>

  <h2>Emergency Contact</h2>
  <table>
    <tr><th>Contact</th><td>${esc(input.emergencyContact ?? "—")}</td></tr>
    <tr><th>Phone</th><td>${esc(input.emergencyPhone ?? "—")}</td></tr>
  </table>

  ${input.notes ? `<h2>Additional Notes</h2><p style="font-size:13px;">${esc(input.notes)}</p>` : ""}

  <div class="alert">
    <strong>Hypo protocol:</strong> If glucose falls below ${input.hypoThresholdMmol} mmol/L, give 15g fast-acting carbohydrate immediately. Recheck in 15 minutes. Contact parent/guardian if not recovered.
  </div>

  <div class="footer">
    <p>GluMira™ is an educational platform, not a medical device. This care plan is for informational purposes. Always follow your clinician's guidance.</p>
  </div>
</body>
</html>`.trim();

  return {
    html,
    patientName: input.patientName,
    generatedAt,
    regimeName: input.regimeName,
    hypoThresholdMgdl: hypoMgdl,
  };
}

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
