#!/usr/bin/env tsx
/**
 * GluMira™ — Supabase Type Generator
 *
 * Generates TypeScript types from the Supabase project schema.
 * Run with: pnpm tsx scripts/generate-types.ts
 *
 * Requires SUPABASE_PROJECT_ID in environment.
 * Output: supabase/types.ts
 */

import { execSync } from "child_process";
import { writeFileSync, existsSync } from "fs";
import { resolve } from "path";

const PROJECT_ID = process.env.SUPABASE_PROJECT_ID;
const OUT_PATH = resolve(__dirname, "../supabase/types.ts");

if (!PROJECT_ID) {
  console.error("❌  SUPABASE_PROJECT_ID is not set in environment");
  console.error("    Add it to .env.local or export it before running this script");
  process.exit(1);
}

console.log(`🔄  Generating types for project: ${PROJECT_ID}`);
console.log(`📄  Output: ${OUT_PATH}`);

try {
  // Check supabase CLI is available
  execSync("supabase --version", { stdio: "pipe" });
} catch {
  console.error("❌  Supabase CLI not found. Install with: npm i -g supabase");
  process.exit(1);
}

try {
  const result = execSync(
    `supabase gen types typescript --project-id ${PROJECT_ID} --schema public`,
    { encoding: "utf-8" }
  );

  const header = `/**
 * GluMira™ — Supabase Generated Types
 * Auto-generated by scripts/generate-types.ts
 * DO NOT EDIT MANUALLY — run \`pnpm generate:types\` to regenerate
 *
 * Generated: ${new Date().toISOString()}
 * Project: ${PROJECT_ID}
 */

`;

  writeFileSync(OUT_PATH, header + result, "utf-8");
  console.log(`✅  Types written to ${OUT_PATH}`);
} catch (err) {
  console.error("❌  Type generation failed:", (err as Error).message);
  process.exit(1);
}
