/**
 * GluMira™ AI Clinician Notes Generator
 * Version: 7.0.0
 * Module: AI-CLIN-NOTES-GEN
 *
 * Generates structured clinical visit summaries from patient data.
 * Designed to save clinicians time by auto-generating notes they can
 * review, edit, and approve — not replace their judgment.
 *
 * Output formats:
 *   - SOAP note (Subjective, Objective, Assessment, Plan)
 *   - Quick Summary (one-paragraph overview)
 *   - Detailed Report (multi-section with metrics)
 *   - School Care Plan (for paediatric patients)
 *
 * Key principle (from user knowledge):
 *   "Educate patients on how their doctors evaluate their efforts,
 *    thereby enhancing the value proposition for GluMira subscriptions."
 *
 * DISCLAIMER: GluMira™ is an educational platform. The science of insulin, made visible. Consult your clinician for any medical advice.
 */

import {
  assembleContext,
  computeMetrics,
  type RawPatientData,
  type ComputedMetrics,
  type AssembledContext,
} from "./rag-context-engine";

// ─── Types ───────────────────────────────────────────────────

export type NoteFormat = "soap" | "quick_summary" | "detailed_report" | "school_care_plan";

export interface GenerateNotesRequest {
  patientData: RawPatientData;
  format: NoteFormat;
  periodDays: number;
  clinicianName?: string;
  additionalContext?: string;
}

export interface GeneratedNote {
  format: NoteFormat;
  title: string;
  content: string;
  sections: NoteSection[];
  metrics: MetricsSummary;
  safetyFlags: string[];
  disclaimer: string;
  generatedAt: string;
  editable: boolean;
}

export interface NoteSection {
  heading: string;
  body: string;
  order: number;
}

export interface MetricsSummary {
  periodDays: number;
  readingCount: number;
  tirPercent: number;
  belowRangePercent: number;
  aboveRangePercent: number;
  meanGlucose: number;
  gmi: number;
  cv: number;
  hypoEvents: number;
  hypoRiskLevel: string;
}

// ─── Constants ───────────────────────────────────────────────

const DISCLAIMER =
  "This note was auto-generated by GluMira™ AI for educational purposes only. " +
  "It is NOT a clinical document and does NOT constitute medical advice. " +
  "The treating clinician must review, edit, and approve before use.";

// ─── Metrics Extraction ─────────────────────────────────────

/**
 * Extract a clean metrics summary from computed metrics.
 */
export function extractMetricsSummary(
  metrics: ComputedMetrics,
  periodDays: number
): MetricsSummary {
  return {
    periodDays,
    readingCount: metrics.readingCount7d,
    tirPercent: metrics.tir.inRange,
    belowRangePercent: Math.round((metrics.tir.low + metrics.tir.veryLow) * 10) / 10,
    aboveRangePercent: Math.round((metrics.tir.high + metrics.tir.veryHigh) * 10) / 10,
    meanGlucose: metrics.tir.mean,
    gmi: metrics.tir.gmi,
    cv: metrics.variability.cv,
    hypoEvents: metrics.hypoRisk.hypoEvents,
    hypoRiskLevel: metrics.hypoRisk.level,
  };
}

/**
 * Generate safety flags based on metrics.
 */
export function generateSafetyFlags(metrics: ComputedMetrics): string[] {
  const flags: string[] = [];

  if (metrics.tir.veryLow > 1) {
    flags.push(`ALERT: Time very low (<54 mg/dL) is ${metrics.tir.veryLow}% — exceeds 1% safety threshold`);
  }
  if (metrics.tir.low + metrics.tir.veryLow > 4) {
    flags.push(`WARNING: Total time below range is ${(metrics.tir.low + metrics.tir.veryLow).toFixed(1)}% — exceeds 4% target`);
  }
  if (metrics.tir.inRange < 70) {
    flags.push(`NOTE: Time in range is ${metrics.tir.inRange}% — below 70% consensus target`);
  }
  if (metrics.variability.isHighVariability) {
    flags.push(`WARNING: High glucose variability (CV: ${metrics.variability.cv}%) — exceeds 36% threshold`);
  }
  if (metrics.hypoRisk.level === "critical") {
    flags.push(`CRITICAL: Hypo risk score ${metrics.hypoRisk.score}/100 — urgent review recommended`);
  } else if (metrics.hypoRisk.level === "high") {
    flags.push(`WARNING: Hypo risk score ${metrics.hypoRisk.score}/100 — clinician review recommended`);
  }

  return flags;
}

// ─── SOAP Note Generator ─────────────────────────────────────

/**
 * Generate a SOAP-format clinical note.
 */
export function generateSOAPNote(
  data: RawPatientData,
  metrics: ComputedMetrics,
  metricsSummary: MetricsSummary,
  safetyFlags: string[],
  periodDays: number
): NoteSection[] {
  const { profile, clinicianNotes } = data;

  // Subjective
  const subjectiveLines = [
    `Patient ${profile.firstName} presents for ${periodDays}-day diabetes management review.`,
    `Diabetes Type: ${profile.diabetesType}.`,
    `CGM Source: ${profile.cgmSource}.`,
    `Current glucose settings: Target ${profile.targetLow}–${profile.targetHigh} ${profile.glucoseUnit}, ISF ${profile.isf}, ICR 1:${profile.icr}, DIA ${profile.diaMinutes} min.`,
  ];
  if (clinicianNotes.length > 0) {
    subjectiveLines.push(`Active clinician notes: ${clinicianNotes.length} on file.`);
  }

  // Objective
  const objectiveLines = [
    `CGM Data: ${metricsSummary.readingCount} readings over ${periodDays} days.`,
    `Time in Range (${profile.targetLow}–${profile.targetHigh}): ${metricsSummary.tirPercent}%`,
    `Time Below Range: ${metricsSummary.belowRangePercent}%`,
    `Time Above Range: ${metricsSummary.aboveRangePercent}%`,
    `Mean Glucose: ${metricsSummary.meanGlucose} ${profile.glucoseUnit}`,
    `GMI (est. A1C): ${metricsSummary.gmi}%`,
    `Coefficient of Variation: ${metricsSummary.cv}%${metrics.variability.isHighVariability ? " [HIGH]" : ""}`,
    `MAGE: ${metrics.variability.mage} ${profile.glucoseUnit}`,
    `Hypo Events: ${metricsSummary.hypoEvents} (Risk: ${metricsSummary.hypoRiskLevel})`,
  ];
  if (metrics.currentGlucose) {
    objectiveLines.push(`Current Glucose: ${metrics.currentGlucose.value} ${profile.glucoseUnit} (${metrics.glucoseTrend.replace(/_/g, " ")})`);
  }
  objectiveLines.push(`Active IOB: ${metrics.activeIOB} units`);

  // Assessment
  const assessmentLines: string[] = [];
  if (metricsSummary.tirPercent >= 70) {
    assessmentLines.push("Time in range meets consensus target (≥70%). Current management appears effective.");
  } else if (metricsSummary.tirPercent >= 50) {
    assessmentLines.push("Time in range is below consensus target. Review of meal timing, carb consistency, and bolus timing may be beneficial.");
  } else {
    assessmentLines.push("Time in range is significantly below target. Comprehensive review of insulin regimen, meal plan, and CGM patterns recommended.");
  }

  if (metrics.variability.isHighVariability) {
    assessmentLines.push("High glucose variability suggests inconsistent carb intake or insulin timing. Law of Small Numbers approach may help.");
  }

  if (safetyFlags.length > 0) {
    assessmentLines.push("Safety flags:");
    safetyFlags.forEach((f) => assessmentLines.push(`  • ${f}`));
  }

  // Plan
  const planLines = [
    "1. Review and discuss CGM patterns with patient.",
    "2. Evaluate current insulin settings (ISF, ICR, basal rates).",
  ];
  if (metricsSummary.tirPercent < 70) {
    planLines.push("3. Consider adjusting meal plan consistency per Bernstein principles.");
  }
  if (metrics.variability.isHighVariability) {
    planLines.push(`${planLines.length + 1}. Address glucose variability — review carb counting accuracy and bolus timing.`);
  }
  if (metricsSummary.hypoRiskLevel === "high" || metricsSummary.hypoRiskLevel === "critical") {
    planLines.push(`${planLines.length + 1}. PRIORITY: Address hypoglycaemia risk — review overnight basals and correction factors.`);
  }
  planLines.push(`${planLines.length + 1}. Follow-up in ${periodDays <= 7 ? "1 week" : "2–4 weeks"}.`);

  return [
    { heading: "Subjective", body: subjectiveLines.join("\n"), order: 1 },
    { heading: "Objective", body: objectiveLines.join("\n"), order: 2 },
    { heading: "Assessment", body: assessmentLines.join("\n"), order: 3 },
    { heading: "Plan", body: planLines.join("\n"), order: 4 },
  ];
}

// ─── Quick Summary Generator ─────────────────────────────────

export function generateQuickSummary(
  data: RawPatientData,
  metrics: ComputedMetrics,
  metricsSummary: MetricsSummary,
  periodDays: number
): NoteSection[] {
  const { profile } = data;

  const tirStatus = metricsSummary.tirPercent >= 70 ? "on target" : "below target";
  const variabilityStatus = metrics.variability.isHighVariability ? "high variability" : "acceptable variability";
  const hypoStatus = metricsSummary.hypoRiskLevel === "low" ? "low hypo risk" : `${metricsSummary.hypoRiskLevel} hypo risk`;

  const summary = [
    `${profile.firstName} (${profile.diabetesType}) — ${periodDays}-day review.`,
    `TIR: ${metricsSummary.tirPercent}% (${tirStatus}), Mean: ${metricsSummary.meanGlucose} ${profile.glucoseUnit}, GMI: ${metricsSummary.gmi}%.`,
    `CV: ${metricsSummary.cv}% (${variabilityStatus}), ${hypoStatus} (${metricsSummary.hypoEvents} events).`,
    `Active IOB: ${metrics.activeIOB} units. CGM: ${profile.cgmSource}.`,
    metricsSummary.tirPercent >= 70
      ? "Current management appears effective. Continue monitoring."
      : "Management review recommended. Consider adjusting insulin settings or meal consistency.",
  ].join(" ");

  return [{ heading: "Summary", body: summary, order: 1 }];
}

// ─── Detailed Report Generator ───────────────────────────────

export function generateDetailedReport(
  data: RawPatientData,
  metrics: ComputedMetrics,
  metricsSummary: MetricsSummary,
  safetyFlags: string[],
  periodDays: number
): NoteSection[] {
  const { profile, clinicianNotes } = data;

  const sections: NoteSection[] = [
    {
      heading: "Patient Overview",
      body: [
        `Name: ${profile.firstName}`,
        `Diabetes Type: ${profile.diabetesType}`,
        `CGM Source: ${profile.cgmSource}`,
        `Review Period: ${periodDays} days`,
        `Total Readings: ${metricsSummary.readingCount}`,
        `Last Sync: ${profile.lastSyncAt ?? "N/A"}`,
      ].join("\n"),
      order: 1,
    },
    {
      heading: "Glucose Settings",
      body: [
        `Target Range: ${profile.targetLow}–${profile.targetHigh} ${profile.glucoseUnit}`,
        `ISF: ${profile.isf} ${profile.glucoseUnit}/unit`,
        `ICR: 1:${profile.icr} (${profile.icr}g per unit)`,
        `DIA: ${profile.diaMinutes} minutes (${(profile.diaMinutes / 60).toFixed(1)} hours)`,
      ].join("\n"),
      order: 2,
    },
    {
      heading: "Time in Range Analysis",
      body: [
        `Very Low (<54): ${metrics.tir.veryLow}%`,
        `Low (54–${profile.targetLow}): ${metrics.tir.low}%`,
        `In Range (${profile.targetLow}–${profile.targetHigh}): ${metrics.tir.inRange}% ${metricsSummary.tirPercent >= 70 ? "✓" : "⚠"}`,
        `High (${profile.targetHigh}–250): ${metrics.tir.high}%`,
        `Very High (>250): ${metrics.tir.veryHigh}%`,
        ``,
        `Mean Glucose: ${metricsSummary.meanGlucose} ${profile.glucoseUnit}`,
        `GMI (est. A1C): ${metricsSummary.gmi}%`,
      ].join("\n"),
      order: 3,
    },
    {
      heading: "Glucose Variability",
      body: [
        `Coefficient of Variation: ${metrics.variability.cv}% ${metrics.variability.isHighVariability ? "[HIGH — exceeds 36%]" : "[within target]"}`,
        `Standard Deviation: ${metrics.variability.sd} ${profile.glucoseUnit}`,
        `MAGE: ${metrics.variability.mage} ${profile.glucoseUnit}`,
      ].join("\n"),
      order: 4,
    },
    {
      heading: "Hypoglycaemia Risk",
      body: [
        `Risk Score: ${metrics.hypoRisk.score}/100`,
        `Risk Level: ${metrics.hypoRisk.level.toUpperCase()}`,
        `Hypo Events: ${metrics.hypoRisk.hypoEvents}`,
      ].join("\n"),
      order: 5,
    },
    {
      heading: "Current Status",
      body: [
        metrics.currentGlucose
          ? `Current Glucose: ${metrics.currentGlucose.value} ${profile.glucoseUnit} (${metrics.glucoseTrend.replace(/_/g, " ")})`
          : "Current Glucose: No recent reading",
        `Active IOB: ${metrics.activeIOB} units`,
        `Last Dose: ${metrics.lastDoseAt ?? "N/A"}`,
        `Last Meal: ${metrics.lastMealAt ?? "N/A"}`,
      ].join("\n"),
      order: 6,
    },
  ];

  // Safety flags section
  if (safetyFlags.length > 0) {
    sections.push({
      heading: "Safety Flags",
      body: safetyFlags.map((f) => `• ${f}`).join("\n"),
      order: 7,
    });
  }

  // Clinician notes section
  if (clinicianNotes.length > 0) {
    sections.push({
      heading: "Active Clinician Notes",
      body: clinicianNotes
        .map((n, i) => `${i + 1}. [${n.category.toUpperCase()}] ${n.body} (${n.createdAt})`)
        .join("\n"),
      order: 8,
    });
  }

  return sections;
}

// ─── School Care Plan Generator ──────────────────────────────

export function generateSchoolCarePlan(
  data: RawPatientData,
  metrics: ComputedMetrics,
  metricsSummary: MetricsSummary
): NoteSection[] {
  const { profile } = data;

  return [
    {
      heading: "Student Information",
      body: [
        `Name: ${profile.firstName}`,
        `Diabetes Type: ${profile.diabetesType}`,
        `Monitoring Device: ${profile.cgmSource === "dexcom" ? "Dexcom CGM" : profile.cgmSource === "nightscout" ? "Nightscout CGM" : "Manual Testing"}`,
      ].join("\n"),
      order: 1,
    },
    {
      heading: "Target Blood Sugar Range",
      body: [
        `Target: ${profile.targetLow}–${profile.targetHigh} ${profile.glucoseUnit}`,
        `Low Alert: Below ${profile.targetLow} ${profile.glucoseUnit}`,
        `High Alert: Above ${profile.targetHigh} ${profile.glucoseUnit}`,
        `Severe Low: Below 54 ${profile.glucoseUnit} — REQUIRES IMMEDIATE ACTION`,
      ].join("\n"),
      order: 2,
    },
    {
      heading: "Insulin Information",
      body: [
        `Insulin Sensitivity Factor (ISF): ${profile.isf} ${profile.glucoseUnit} per unit`,
        `Insulin-to-Carb Ratio (ICR): 1 unit per ${profile.icr}g carbs`,
        `Duration of Insulin Action: ${profile.diaMinutes} minutes`,
        ``,
        `IMPORTANT: School staff should NOT administer insulin corrections without explicit parent/guardian or clinician instruction.`,
      ].join("\n"),
      order: 3,
    },
    {
      heading: "Low Blood Sugar (Hypoglycaemia) Protocol",
      body: [
        `If blood sugar is below ${profile.targetLow} ${profile.glucoseUnit}:`,
        `1. Give 15g of fast-acting carbohydrates (glucose tablets preferred)`,
        `2. Wait 15 minutes and re-test`,
        `3. Repeat if still below ${profile.targetLow} ${profile.glucoseUnit}`,
        `4. If below 54 ${profile.glucoseUnit} or student is confused/unconscious: CALL EMERGENCY SERVICES`,
        ``,
        `Signs of low blood sugar: shakiness, sweating, confusion, pale skin, irritability`,
      ].join("\n"),
      order: 4,
    },
    {
      heading: "High Blood Sugar (Hyperglycaemia) Protocol",
      body: [
        `If blood sugar is above ${profile.targetHigh} ${profile.glucoseUnit}:`,
        `1. Allow student to drink water`,
        `2. Allow bathroom access`,
        `3. Contact parent/guardian if above 300 ${profile.glucoseUnit}`,
        `4. If student has nausea, vomiting, or fruity breath: CALL EMERGENCY SERVICES (possible DKA)`,
      ].join("\n"),
      order: 5,
    },
    {
      heading: "Recent Glucose Performance",
      body: [
        `Time in Range: ${metricsSummary.tirPercent}%`,
        `Average Glucose: ${metricsSummary.meanGlucose} ${profile.glucoseUnit}`,
        `Hypo Events (recent): ${metricsSummary.hypoEvents}`,
        `Hypo Risk Level: ${metricsSummary.hypoRiskLevel}`,
      ].join("\n"),
      order: 6,
    },
    {
      heading: "Emergency Contacts",
      body: [
        `Parent/Guardian: [To be completed by parent]`,
        `Diabetes Care Team: [To be completed by clinician]`,
        `Emergency Services: 911 / local emergency number`,
      ].join("\n"),
      order: 7,
    },
  ];
}

// ─── Main Generator ──────────────────────────────────────────

/**
 * Generate a clinical note in the requested format.
 * This is the main entry point for the Clinician Notes Generator.
 */
export function generateClinicianNote(request: GenerateNotesRequest): GeneratedNote {
  const { patientData, format, periodDays } = request;

  const metrics = computeMetrics(patientData);
  const metricsSummary = extractMetricsSummary(metrics, periodDays);
  const safetyFlags = generateSafetyFlags(metrics);

  let sections: NoteSection[];
  let title: string;

  switch (format) {
    case "soap":
      title = `SOAP Note — ${patientData.profile.firstName} — ${periodDays}-Day Review`;
      sections = generateSOAPNote(patientData, metrics, metricsSummary, safetyFlags, periodDays);
      break;

    case "quick_summary":
      title = `Quick Summary — ${patientData.profile.firstName} — ${periodDays}-Day Review`;
      sections = generateQuickSummary(patientData, metrics, metricsSummary, periodDays);
      break;

    case "detailed_report":
      title = `Detailed Report — ${patientData.profile.firstName} — ${periodDays}-Day Review`;
      sections = generateDetailedReport(patientData, metrics, metricsSummary, safetyFlags, periodDays);
      break;

    case "school_care_plan":
      title = `School Care Plan — ${patientData.profile.firstName}`;
      sections = generateSchoolCarePlan(patientData, metrics, metricsSummary);
      break;

    default:
      throw new Error(`Unknown note format: ${format}`);
  }

  const content = sections
    .sort((a, b) => a.order - b.order)
    .map((s) => `## ${s.heading}\n\n${s.body}`)
    .join("\n\n---\n\n");

  return {
    format,
    title,
    content,
    sections,
    metrics: metricsSummary,
    safetyFlags,
    disclaimer: DISCLAIMER,
    generatedAt: new Date().toISOString(),
    editable: true,
  };
}

/**
 * Generate an AI-enhanced clinical note using the LLM for narrative sections.
 * Falls back to the template-based generator if the LLM is unavailable.
 */
export async function generateAIEnhancedNote(
  request: GenerateNotesRequest,
  invokeLLM: (messages: Array<{ role: string; content: string }>) => Promise<string>
): Promise<GeneratedNote> {
  // First generate the template-based note
  const baseNote = generateClinicianNote(request);

  // Try to enhance the assessment section with AI narrative
  try {
    const context = assembleContext(request.patientData);

    const messages = [
      {
        role: "system",
        content: `You are GluMira™ AI generating a clinical note enhancement. 
You have access to the patient's real data. Write a brief, professional clinical narrative 
summarizing the key patterns and observations. Use plain medical language suitable for a 
clinician review. Do NOT suggest specific doses. Do NOT diagnose. Keep it under 200 words.

${context.patientSummary}
${context.analyticsBlock}`,
      },
      {
        role: "user",
        content: `Generate a brief clinical narrative for this ${request.periodDays}-day review. 
Format: ${request.format}. Focus on: patterns of concern, positive trends, and areas for discussion.`,
      },
    ];

    const aiNarrative = await invokeLLM(messages);

    // Add AI narrative as an additional section
    baseNote.sections.push({
      heading: "AI-Generated Clinical Narrative",
      body: aiNarrative + "\n\n_[AI-generated — review before use]_",
      order: baseNote.sections.length + 1,
    });

    // Rebuild content with the new section
    baseNote.content = baseNote.sections
      .sort((a, b) => a.order - b.order)
      .map((s) => `## ${s.heading}\n\n${s.body}`)
      .join("\n\n---\n\n");

  } catch {
    // LLM unavailable — return template-based note without AI enhancement
    // This is fine — the template note is already comprehensive
  }

  return baseNote;
}
